apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eddyv3
  namespace: eddyv3-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eddyv3
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
